from app import db
from datetime import datetime

class Stock(db.Model):
    """Model for stock symbols and their configuration"""
    id = db.Column(db.Integer, primary_key=True)
    symbol = db.Column(db.String(20), unique=True, nullable=False)
    name = db.Column(db.String(100), nullable=False)
    active = db.Column(db.Boolean, default=True)
    added_on = db.Column(db.DateTime, default=datetime.utcnow)
    
    # Relationship: one stock can have many signals
    signals = db.relationship('Signal', backref='stock', lazy=True, cascade="all, delete-orphan")
    
    def __repr__(self):
        return f"<Stock {self.symbol}>"

class Signal(db.Model):
    """Model for trading signals generated by the system"""
    id = db.Column(db.Integer, primary_key=True)
    stock_id = db.Column(db.Integer, db.ForeignKey('stock.id'), nullable=False)
    signal_type = db.Column(db.String(10), nullable=False)  # BUY or SELL
    price = db.Column(db.Float, nullable=False)
    rsi = db.Column(db.Float, nullable=False)
    ema = db.Column(db.Float, nullable=False)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)
    message_sent = db.Column(db.Boolean, default=False)
    
    def __repr__(self):
        return f"<Signal {self.signal_type} for {self.stock.symbol} at {self.price}>"
